openapi: 3.0.3
info:
  title: Swagger Test
  description: |-
    This is a sample Test
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1/
tags:
  - name: test
paths:
  /test:
    get:
      tags:
        - test
      operationId: update
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string